/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/activities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List activities
         * @description Activities whose start day falls between `start` and `end`, most recent first.
         */
        get: operations["get_activities_api_activities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List sports
         * @description The sports found in the activities, sorted by key, with their label and icon.
         */
        get: operations["get_sports_api_sports_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/activities/{activity_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Activity detail
         * @description One activity, with its heart-rate zones, threshold and estimated time per training effect.
         */
        get: operations["get_activity_api_activities__activity_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/activities/{activity_id}/chart": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Activity chart data
         * @description The data of the activity chart: 30-second bins, heart-rate zone bands and pauses.
         *
         *     Empty lists when the activity has no sampled data.
         */
        get: operations["get_activity_chart_api_activities__activity_id__chart_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/activities/{activity_id}/chart/vega": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Activity chart, Vega-Lite
         * @description The activity chart as a ready-to-render Vega-Lite specification.
         */
        get: operations["get_activity_chart_vega_api_activities__activity_id__chart_vega_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/activities/{activity_id}/route": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Activity route
         * @description The GPS track as [lat, lon] pairs. Longer tracks keep one point every N, always
         *     including the first and the last. Empty when the activity has no position.
         */
        get: operations["get_activity_route_api_activities__activity_id__route_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/daily/{day}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Daily data
         * @description Everything known about one day (training, recovery, health, load), as built for the
         *     daily report. Not yet typed field by field: the shape is still changing.
         */
        get: operations["get_daily_api_daily__day__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reports/daily/{day}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Daily report
         * @description The written daily report of `day`, split into its sections.
         */
        get: operations["get_daily_report_api_reports_daily__day__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Activity
         * @description One activity, as stored in the `activities` table.
         */
        Activity: {
            /** Activity Id */
            activity_id: number;
            /** Sport */
            sport: string | null;
            /** Sub Sport */
            sub_sport: string | null;
            /**
             * Start Time
             * Format: date-time
             * @description Local time, no time zone.
             */
            start_time: string;
            /** Activity Name */
            activity_name: string | null;
            /** Total Distance Km */
            total_distance_km: number | null;
            /**
             * Total Time Min
             * @description Elapsed time, pauses included.
             */
            total_time_min: number | null;
            /** Total Ascent M */
            total_ascent_m: number | null;
            /** Total Descent M */
            total_descent_m: number | null;
            /**
             * Avg Speed Kmh
             * @description Average speed over moving time.
             */
            avg_speed_kmh: number | null;
            /**
             * Equiv Speed Kmh
             * @description Average grade-adjusted speed (on-foot sports).
             */
            equiv_speed_kmh: number | null;
            /** Avg Heart Rate */
            avg_heart_rate: number | null;
            /** Max Heart Rate */
            max_heart_rate: number | null;
            /** Total Calories */
            total_calories: number | null;
            /** Vo2Max */
            vo2max: number | null;
            /**
             * Aerobic Te
             * @description Garmin's aerobic Training Effect, 0-5.
             */
            aerobic_te: number | null;
            /**
             * Anaerobic Te
             * @description Garmin's anaerobic Training Effect, 0-5.
             */
            anaerobic_te: number | null;
        };
        /**
         * ActivityDetail
         * @description One activity with its heart-rate settings and estimated effects.
         */
        ActivityDetail: {
            /** Activity Id */
            activity_id: number;
            /** Sport */
            sport: string | null;
            /** Sub Sport */
            sub_sport: string | null;
            /**
             * Start Time
             * Format: date-time
             * @description Local time, no time zone.
             */
            start_time: string;
            /** Activity Name */
            activity_name: string | null;
            /** Total Distance Km */
            total_distance_km: number | null;
            /**
             * Total Time Min
             * @description Elapsed time, pauses included.
             */
            total_time_min: number | null;
            /** Total Ascent M */
            total_ascent_m: number | null;
            /** Total Descent M */
            total_descent_m: number | null;
            /**
             * Avg Speed Kmh
             * @description Average speed over moving time.
             */
            avg_speed_kmh: number | null;
            /**
             * Equiv Speed Kmh
             * @description Average grade-adjusted speed (on-foot sports).
             */
            equiv_speed_kmh: number | null;
            /** Avg Heart Rate */
            avg_heart_rate: number | null;
            /** Max Heart Rate */
            max_heart_rate: number | null;
            /** Total Calories */
            total_calories: number | null;
            /** Vo2Max */
            vo2max: number | null;
            /**
             * Aerobic Te
             * @description Garmin's aerobic Training Effect, 0-5.
             */
            aerobic_te: number | null;
            /**
             * Anaerobic Te
             * @description Garmin's anaerobic Training Effect, 0-5.
             */
            anaerobic_te: number | null;
            /**
             * Hr Zone Bounds
             * @description Upper limits of zones Z1-Z4, in bpm.
             */
            hr_zone_bounds: number[] | null;
            /**
             * Threshold Hr
             * @description Anaerobic threshold, in bpm.
             */
            threshold_hr: number | null;
            /** @description Null when the zones, the threshold or the heart rate are missing. */
            effect_seconds: components["schemas"]["EffectSeconds"] | null;
        };
        /**
         * ChartBin
         * @description One 30-second interval of the activity chart. Times in minutes from the start.
         */
        ChartBin: {
            /** Start */
            start: number;
            /** End */
            end: number;
            /**
             * Minute
             * @description Middle of the interval.
             */
            minute: number;
            /** Hr */
            hr: number | null;
            /**
             * Speed
             * @description Speed, smoothed over 30 s, in km/h.
             */
            speed: number | null;
            /**
             * Equiv
             * @description Grade-adjusted speed, in km/h.
             */
            equiv: number | null;
            /** Slope Pct */
            slope_pct: number | null;
            /** Slope Deg */
            slope_deg: number | null;
        };
        /**
         * ChartData
         * @description The data behind the activity chart, for clients that draw it themselves.
         */
        ChartData: {
            /** Bins */
            bins: components["schemas"]["ChartBin"][];
            /** Zone Bands */
            zone_bands: components["schemas"]["ZoneBand"][];
            /** Pauses */
            pauses: components["schemas"]["Pause"][];
            /** Hr Zone Bounds */
            hr_zone_bounds: number[] | null;
            /** Threshold Hr */
            threshold_hr: number | null;
        };
        /**
         * EffectSeconds
         * @description Seconds spent in each training effect, estimated from heart rate.
         */
        EffectSeconds: {
            /** Low Aerobic S */
            low_aerobic_s: number;
            /** High Aerobic S */
            high_aerobic_s: number;
            /** Anaerobic S */
            anaerobic_s: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * Pause
         * @description A pause in the recording. Times in minutes from the start.
         */
        Pause: {
            /** Start */
            start: number;
            /** End */
            end: number;
        };
        /**
         * Report
         * @description A written daily report, split into its sections.
         */
        Report: {
            /**
             * Day
             * Format: date
             */
            day: string;
            /** Sections */
            sections: components["schemas"]["ReportSection"][];
        };
        /** ReportSection */
        ReportSection: {
            /**
             * Title
             * @description Null for the text before the first section.
             */
            title: string | null;
            /**
             * Body
             * @description Markdown.
             */
            body: string;
            /**
             * Icon
             * @description Icon file name, served under /icons. Null when the section has none.
             */
            icon: string | null;
        };
        /**
         * Route
         * @description The GPS track of an activity.
         */
        Route: {
            /**
             * Points
             * @description [lat, lon] pairs, in recording order.
             */
            points: [
                number,
                number
            ][];
        };
        /**
         * Sport
         * @description A sport found in the activities.
         */
        Sport: {
            /**
             * Sport
             * @description The key used in `Activity.sport`.
             */
            sport: string;
            /**
             * Label
             * @description The name to show.
             */
            label: string;
            /**
             * Icon
             * @description Icon file name, served under /icons.
             */
            icon: string | null;
        };
        /**
         * SportList
         * @description The sports found in the activities, and the icon for rest days.
         */
        SportList: {
            /** Sports */
            sports: components["schemas"]["Sport"][];
            /**
             * Rest Icon
             * @description Icon file name for days without activities, served under /icons.
             */
            rest_icon: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * ZoneBand
         * @description A stretch of time in one heart-rate zone. Times in minutes from the start.
         */
        ZoneBand: {
            /** Start */
            start: number;
            /** End */
            end: number;
            /**
             * Zone
             * @description Heart-rate zone, 1-5.
             */
            zone: number;
            /**
             * Hr
             * @description Average heart rate in the band, in bpm.
             */
            hr: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_activities_api_activities_get: {
        parameters: {
            query?: {
                /** @description First day, included. Default: 27 days before `end`. */
                start?: string | null;
                /** @description Last day, included. Default: today. */
                end?: string | null;
                /** @description Keep only these sports. Repeatable. */
                sport?: string[] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Activity"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_sports_api_sports_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SportList"];
                };
            };
        };
    };
    get_activity_api_activities__activity_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                activity_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivityDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_activity_chart_api_activities__activity_id__chart_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                activity_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChartData"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_activity_chart_vega_api_activities__activity_id__chart_vega_get: {
        parameters: {
            query?: {
                theme?: "light" | "dark";
            };
            header?: never;
            path: {
                activity_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_activity_route_api_activities__activity_id__route_get: {
        parameters: {
            query?: {
                /** @description Upper limit on the number of points. */
                max_points?: number;
            };
            header?: never;
            path: {
                activity_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Route"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_daily_api_daily__day__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                day: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_daily_report_api_reports_daily__day__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                day: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Report"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
