/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/activities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List activities
         * @description Activities whose start day falls between `start` and `end`, most recent first.
         */
        get: operations["get_activities_api_activities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List sports
         * @description The sports found in the activities, sorted by key, with their label and icon.
         */
        get: operations["get_sports_api_sports_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/activities/{activity_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Activity detail
         * @description One activity, with its heart-rate zones, threshold and estimated time per training effect.
         */
        get: operations["get_activity_api_activities__activity_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/activities/{activity_id}/chart": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Activity chart data
         * @description The data of the activity chart: 30-second bins, heart-rate zone bands and pauses.
         *
         *     Empty lists when the activity has no sampled data.
         */
        get: operations["get_activity_chart_api_activities__activity_id__chart_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/activities/{activity_id}/chart/vega": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Activity chart, Vega-Lite
         * @description The activity chart as a ready-to-render Vega-Lite specification.
         */
        get: operations["get_activity_chart_vega_api_activities__activity_id__chart_vega_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/activities/{activity_id}/route": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Activity route
         * @description The GPS track as [lat, lon] pairs. Longer tracks keep one point every N, always
         *     including the first and the last. Empty when the activity has no position.
         */
        get: operations["get_activity_route_api_activities__activity_id__route_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/daily/{day}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Daily data
         * @description Everything known about one day (training, recovery, health, load), as built for the
         *     daily report.
         */
        get: operations["get_daily_api_daily__day__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reports/daily/{day}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Daily report
         * @description The written daily report of `day`, split into its sections.
         */
        get: operations["get_daily_report_api_reports_daily__day__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Activity
         * @description One activity, as stored in the `activities` table.
         */
        Activity: {
            /** Activity Id */
            activity_id: number;
            /** Sport */
            sport: string | null;
            /** Sub Sport */
            sub_sport: string | null;
            /**
             * Start Time
             * Format: date-time
             * @description Local time, no time zone.
             */
            start_time: string;
            /** Activity Name */
            activity_name: string | null;
            /** Total Distance Km */
            total_distance_km: number | null;
            /**
             * Total Time Min
             * @description Elapsed time, pauses included.
             */
            total_time_min: number | null;
            /** Total Ascent M */
            total_ascent_m: number | null;
            /** Total Descent M */
            total_descent_m: number | null;
            /**
             * Avg Speed Kmh
             * @description Average speed over moving time.
             */
            avg_speed_kmh: number | null;
            /**
             * Equiv Speed Kmh
             * @description Average grade-adjusted speed (on-foot sports).
             */
            equiv_speed_kmh: number | null;
            /** Avg Heart Rate */
            avg_heart_rate: number | null;
            /** Max Heart Rate */
            max_heart_rate: number | null;
            /** Total Calories */
            total_calories: number | null;
            /** Vo2Max */
            vo2max: number | null;
            /**
             * Aerobic Te
             * @description Garmin's aerobic Training Effect, 0-5.
             */
            aerobic_te: number | null;
            /**
             * Anaerobic Te
             * @description Garmin's anaerobic Training Effect, 0-5.
             */
            anaerobic_te: number | null;
        };
        /**
         * ActivityDetail
         * @description One activity with its heart-rate settings and estimated effects.
         */
        ActivityDetail: {
            /** Activity Id */
            activity_id: number;
            /** Sport */
            sport: string | null;
            /** Sub Sport */
            sub_sport: string | null;
            /**
             * Start Time
             * Format: date-time
             * @description Local time, no time zone.
             */
            start_time: string;
            /** Activity Name */
            activity_name: string | null;
            /** Total Distance Km */
            total_distance_km: number | null;
            /**
             * Total Time Min
             * @description Elapsed time, pauses included.
             */
            total_time_min: number | null;
            /** Total Ascent M */
            total_ascent_m: number | null;
            /** Total Descent M */
            total_descent_m: number | null;
            /**
             * Avg Speed Kmh
             * @description Average speed over moving time.
             */
            avg_speed_kmh: number | null;
            /**
             * Equiv Speed Kmh
             * @description Average grade-adjusted speed (on-foot sports).
             */
            equiv_speed_kmh: number | null;
            /** Avg Heart Rate */
            avg_heart_rate: number | null;
            /** Max Heart Rate */
            max_heart_rate: number | null;
            /** Total Calories */
            total_calories: number | null;
            /** Vo2Max */
            vo2max: number | null;
            /**
             * Aerobic Te
             * @description Garmin's aerobic Training Effect, 0-5.
             */
            aerobic_te: number | null;
            /**
             * Anaerobic Te
             * @description Garmin's anaerobic Training Effect, 0-5.
             */
            anaerobic_te: number | null;
            /**
             * Hr Zone Bounds
             * @description Upper limits of zones Z1-Z4, in bpm.
             */
            hr_zone_bounds: number[] | null;
            /**
             * Threshold Hr
             * @description Anaerobic threshold, in bpm.
             */
            threshold_hr: number | null;
            /** @description Null when the zones, the threshold or the heart rate are missing. */
            effect_seconds: components["schemas"]["EffectSeconds"] | null;
        };
        /**
         * Alert
         * @description A warning sign, with its own numbers in extra fields.
         */
        Alert: {
            /** Kind */
            kind: string;
            /** Detail */
            detail: string;
        } & {
            [key: string]: unknown;
        };
        /**
         * ChartBin
         * @description One 30-second interval of the activity chart. Times in minutes from the start.
         */
        ChartBin: {
            /** Start */
            start: number;
            /** End */
            end: number;
            /**
             * Minute
             * @description Middle of the interval.
             */
            minute: number;
            /** Hr */
            hr: number | null;
            /**
             * Speed
             * @description Speed, smoothed over 30 s, in km/h.
             */
            speed: number | null;
            /**
             * Equiv
             * @description Grade-adjusted speed, in km/h.
             */
            equiv: number | null;
            /** Slope Pct */
            slope_pct: number | null;
            /** Slope Deg */
            slope_deg: number | null;
        };
        /**
         * ChartData
         * @description The data behind the activity chart, for clients that draw it themselves.
         */
        ChartData: {
            /** Bins */
            bins: components["schemas"]["ChartBin"][];
            /** Zone Bands */
            zone_bands: components["schemas"]["ZoneBand"][];
            /** Pauses */
            pauses: components["schemas"]["Pause"][];
            /** Hr Zone Bounds */
            hr_zone_bounds: number[] | null;
            /** Threshold Hr */
            threshold_hr: number | null;
        };
        /**
         * DailyData
         * @description Everything known about one day, as built for the daily report.
         */
        DailyData: {
            /**
             * Day
             * Format: date
             */
            day: string;
            /** Weekday */
            weekday: string;
            /** Health Data Up To */
            health_data_up_to: string | null;
            morning: components["schemas"]["Morning"];
            /**
             * Sleep Minutes
             * @description Last night's sleep in whole minutes (sleep_hours is rounded to 0.1 h).
             */
            sleep_minutes: number | null;
            sleep_last_7: components["schemas"]["SleepLast7"];
            /**
             * Alerts
             * @description Empty when there are no warning signs.
             */
            alerts: components["schemas"]["Alert"][];
            load: components["schemas"]["Load"];
            /** Sessions */
            sessions: {
                [key: string]: unknown;
            };
            recent: components["schemas"]["Recent"];
            /** Hr Zones */
            hr_zones: {
                [key: string]: unknown;
            } | null;
            /** Missing */
            missing: string[];
        };
        /** DayActivities */
        DayActivities: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Weekday */
            weekday: string;
            /**
             * Activities
             * @description One line per activity, e.g. "running 8.1 km".
             */
            activities: string[];
        };
        /**
         * EffectSeconds
         * @description Seconds spent in each training effect, estimated from heart rate.
         */
        EffectSeconds: {
            /** Low Aerobic S */
            low_aerobic_s: number;
            /** High Aerobic S */
            high_aerobic_s: number;
            /** Anaerobic S */
            anaerobic_s: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Load */
        Load: {
            now: components["schemas"]["LoadNow"] | null;
            /** @description Null when the health files have no targets. */
            targets: components["schemas"]["LoadTargets"] | null;
            week_ago: components["schemas"]["LoadNow"] | null;
            /** @description Only when VO2max moved by 0.5 or more in 28 days. */
            vo2max_change: components["schemas"]["Vo2maxChange"] | null;
        };
        /**
         * LoadNow
         * @description Garmin's training load as of one day.
         */
        LoadNow: {
            /**
             * As Of
             * Format: date
             */
            as_of: string;
            /** Load Acute */
            load_acute: number | null;
            /** Load Chronic */
            load_chronic: number | null;
            /** Acwr */
            acwr: number | null;
            /** Acwr Status */
            acwr_status: string | null;
            /** Training Status */
            training_status: number | null;
            /** Training Status Phrase */
            training_status_phrase: string | null;
            /**
             * Load Aerobic Low
             * @description Monthly load, low aerobic.
             */
            load_aerobic_low: number | null;
            /**
             * Load Aerobic High
             * @description Monthly load, high aerobic.
             */
            load_aerobic_high: number | null;
            /**
             * Load Anaerobic
             * @description Monthly load, anaerobic.
             */
            load_anaerobic: number | null;
            /** Load Balance Phrase */
            load_balance_phrase: string | null;
        };
        /**
         * LoadTargets
         * @description Garmin's target ranges for the monthly load of each effect.
         */
        LoadTargets: {
            load_aerobic_low: components["schemas"]["TargetRange"];
            load_aerobic_high: components["schemas"]["TargetRange"];
            load_anaerobic: components["schemas"]["TargetRange"];
        };
        /**
         * Mean
         * @description An average over a window, with the number of days it is made of.
         */
        Mean: {
            /**
             * Mean
             * @description Null when no day in the window has a value.
             */
            mean: number | null;
            /** Days */
            days: number;
        };
        /**
         * Measure
         * @description One morning measure, with its 7- and 28-day averages.
         */
        Measure: {
            /** Value */
            value: number | null;
            /**
             * Date
             * Format: date
             * @description The day the value is read from.
             */
            date: string;
            avg_7d: components["schemas"]["Mean"];
            avg_28d: components["schemas"]["Mean"];
            /** Delta Vs 28D */
            delta_vs_28d: number | null;
        };
        /**
         * Morning
         * @description Recovery and health measures of the morning. Stress and the body battery low are the
         *     day before's; everything else is the night/morning of the day.
         */
        Morning: {
            readiness: components["schemas"]["Measure"];
            resting_hr: components["schemas"]["Measure"];
            hrv_last_night: components["schemas"]["Measure"];
            hrv_weekly_avg: components["schemas"]["Measure"];
            resp_sleep: components["schemas"]["Measure"];
            sleep_hours: components["schemas"]["Measure"];
            sleep_score: components["schemas"]["Measure"];
            stress_avg_yesterday: components["schemas"]["Measure"];
            body_battery_morning: components["schemas"]["Measure"];
            body_battery_low_yesterday: components["schemas"]["Measure"];
            spo2_avg: components["schemas"]["Measure"];
            /**
             * Hrv Status
             * @description Garmin's word for the HRV status.
             */
            hrv_status: string | null;
            /** @description Garmin's balanced HRV range, in ms. */
            hrv_baseline: components["schemas"]["Range"] | null;
        };
        /**
         * Pause
         * @description A pause in the recording. Times in minutes from the start.
         */
        Pause: {
            /** Start */
            start: number;
            /** End */
            end: number;
        };
        /** Range */
        Range: {
            /** Low */
            low: number;
            /** High */
            high: number;
        };
        /**
         * Recent
         * @description The days before the day. Counts ignore what was done on the day itself.
         */
        Recent: {
            /** Trained Today */
            trained_today: boolean;
            /** Last Activity Before Today */
            last_activity_before_today: string | null;
            /** Days Since Last Activity Before Today */
            days_since_last_activity_before_today: number | null;
            /** Last Hard Session Before Today */
            last_hard_session_before_today: string | null;
            /** Days Since Last Hard Session Before Today */
            days_since_last_hard_session_before_today: number | null;
            /** Hard Session Rule */
            hard_session_rule: string;
            /** Rest Days Last 7 */
            rest_days_last_7: number;
            /** Consecutive Training Days Before Today */
            consecutive_training_days_before_today: number;
            /** Consecutive Rest Days Before Today */
            consecutive_rest_days_before_today: number;
            /** Last 7 Days */
            last_7_days: components["schemas"]["DayActivities"][];
            /** Activities Last 14 Days */
            activities_last_14_days: components["schemas"]["RecentActivity"][];
        };
        /** RecentActivity */
        RecentActivity: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Sport */
            sport: string | null;
            /** Distance Km */
            distance_km: number | null;
            /** Duration Min */
            duration_min: number | null;
            /** Aerobic Te */
            aerobic_te: number | null;
            /** Anaerobic Te */
            anaerobic_te: number | null;
        };
        /**
         * Report
         * @description A written daily report, split into its sections.
         */
        Report: {
            /**
             * Day
             * Format: date
             */
            day: string;
            /** Sections */
            sections: components["schemas"]["ReportSection"][];
        };
        /** ReportSection */
        ReportSection: {
            /**
             * Title
             * @description Null for the text before the first section.
             */
            title: string | null;
            /**
             * Body
             * @description Markdown.
             */
            body: string;
            /**
             * Icon
             * @description Icon file name, served under /icons. Null when the section has none.
             */
            icon: string | null;
        };
        /**
         * Route
         * @description The GPS track of an activity.
         */
        Route: {
            /**
             * Points
             * @description [lat, lon] pairs, in recording order.
             */
            points: [
                number,
                number
            ][];
        };
        /** SleepLast7 */
        SleepLast7: {
            /**
             * Hours
             * @description Hours of sleep, night by night.
             */
            hours: {
                [key: string]: number | null;
            };
            /**
             * Short Nights
             * @description Nights under 7 h.
             */
            short_nights: number;
            /** Nights Measured */
            nights_measured: number;
        };
        /**
         * Sport
         * @description A sport found in the activities.
         */
        Sport: {
            /**
             * Sport
             * @description The key used in `Activity.sport`.
             */
            sport: string;
            /**
             * Label
             * @description The name to show.
             */
            label: string;
            /**
             * Icon
             * @description Icon file name, served under /icons.
             */
            icon: string | null;
        };
        /**
         * SportList
         * @description The sports found in the activities, and the icon for rest days.
         */
        SportList: {
            /** Sports */
            sports: components["schemas"]["Sport"][];
            /**
             * Rest Icon
             * @description Icon file name for days without activities, served under /icons.
             */
            rest_icon: string;
        };
        /** TargetRange */
        TargetRange: {
            /** Min */
            min: number;
            /** Max */
            max: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** Vo2maxChange */
        Vo2maxChange: {
            /** Now */
            now: number;
            /** Days Ago 28 */
            days_ago_28: number;
            /** Change */
            change: number;
        };
        /**
         * ZoneBand
         * @description A stretch of time in one heart-rate zone. Times in minutes from the start.
         */
        ZoneBand: {
            /** Start */
            start: number;
            /** End */
            end: number;
            /**
             * Zone
             * @description Heart-rate zone, 1-5.
             */
            zone: number;
            /**
             * Hr
             * @description Average heart rate in the band, in bpm.
             */
            hr: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_activities_api_activities_get: {
        parameters: {
            query?: {
                /** @description First day, included. Default: 27 days before `end`. */
                start?: string | null;
                /** @description Last day, included. Default: today. */
                end?: string | null;
                /** @description Keep only these sports. Repeatable. */
                sport?: string[] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Activity"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_sports_api_sports_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SportList"];
                };
            };
        };
    };
    get_activity_api_activities__activity_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                activity_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivityDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_activity_chart_api_activities__activity_id__chart_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                activity_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChartData"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_activity_chart_vega_api_activities__activity_id__chart_vega_get: {
        parameters: {
            query?: {
                theme?: "light" | "dark";
            };
            header?: never;
            path: {
                activity_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_activity_route_api_activities__activity_id__route_get: {
        parameters: {
            query?: {
                /** @description Upper limit on the number of points. */
                max_points?: number;
            };
            header?: never;
            path: {
                activity_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Route"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_daily_api_daily__day__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                day: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DailyData"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_daily_report_api_reports_daily__day__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                day: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Report"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
